# Generated by Django 2.2.7 on 2019-11-30 11:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallica',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gallica_url', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('wiki_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('summary_en', models.TextField(blank=True, null=True)),
                ('summary_fr', models.TextField(blank=True, null=True)),
                ('gallica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Gallica')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=20, null=True)),
                ('gallica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Gallica')),
            ],
        ),
    ]
